### ISSUE TITLE
Add test cases for extreme / invalid user inputs in the feature tests.

### ISSUE THREAD

**Issue by andela-bmakinwa** [andela-gogbara/Shortr#27]
In your feature tests, the only contexts / test cases catered for were with valid inputs. Add more test cases to cater for extreme and invalid inputs.

**Comment by andela-gogbara** [comment]
Added a more robust test for user creation.

**Comment by andela-gogbara** [comment]
Added a more robust test for user creation that has context for both valid inputs and invalid inputs.
