### ISSUE TITLE
Inappropriate commit message

### ISSUE THREAD

**Issue by andela-bmakinwa** [andela-gogbara/Shortr#32]
Why do you have the commit message `jssks`?
Commit messages are important for the following reasons: 
- To speed up the reviewing process
- To help us write a good release note.
- To help the future maintainers to find out why a particular change was made to the code or why a specific feature was added.

**Comment by andela-gogbara** [comment]
I was supposed to squash the commit message into another commit with a more descriptive message of the changes I made.
