### ISSUE TITLE
Inconsistent commit format

### ISSUE THREAD

**Issue by andela-bmakinwa** [andela-gogbara/Shortr#35]
Your commit messages don't follow any convention (new or existing). It is very important to follow a convention and be consistent with it.

**Comment by andela-gogbara** [comment]
When I started the project I was still following the old commit convention(even in my PRs) after you corrected me I started using the new format.

**Comment by andela-gogbara** [comment]
I have corrected all commit messages with errors.

**Comment by makinwab** [comment]
👍
